variables:
    COMPOSER_ALLOW_SUPERUSER: 1

stages:
    - lint
    - deploy

lint_php:
    stage: lint
    image: git.cec.valantic.com:5050/valantic-pimcore/docker-images/php:8.1-alpine

    before_script:
        - composer install

    script:
        - exit 0 # Fixme ASAP
        - composer run php-cs-fixer-check
        - composer run phpstan
        - composer run test

    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - vendor/
            - vendor-bin/**/vendor/

    artifacts:
        when: always
        reports:
            junit: report.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage.cobertura.xml

lint_js:
    stage: lint
    image: git.cec.valantic.com:5050/valantic-pimcore/docker-images/node:lts

    before_script:
        - npm i

    script:
        - npm run lint

    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - node_modules/

deploy:
    stage: deploy
    image: git.cec.valantic.com:5050/valantic-pimcore/docker-images/php:8.1-alpine
    only:
        - tags
    script:
        - 'apk add --update git bash xz curl'
        - 'curl -k --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
