services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Valantic\PimcoreApiDocumentationBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    #    Valantic\PimcoreApiDocumentationBundle\ExampleClass:
    #        arguments:
    #            - "@service_id"
    #            - "plain_value"
    #            - "%parameter%"

    Valantic\PimcoreApiDocumentationBundle\Service\DataTypeParser\:
        resource: '../../Service/DataTypeParser'
        tags: ['valantic.pimcore_api_doc.data_type_parser']

    Valantic\PimcoreApiDocumentationBundle\Command\DocGeneratorCommand: ~

    Valantic\PimcoreApiDocumentationBundle\Contract\Service\DocsGeneratorInterface:
        class: Valantic\PimcoreApiDocumentationBundle\Service\DocsGenerator

    Valantic\PimcoreApiDocumentationBundle\Contract\Service\ControllerMethodParserInterface:
        class: Valantic\PimcoreApiDocumentationBundle\Service\ControllerMethodParser

    Valantic\PimcoreApiDocumentationBundle\Contract\Service\SchemaGeneratorInterface:
        class: Valantic\PimcoreApiDocumentationBundle\Service\SchemaGenerator

    Valantic\PimcoreApiDocumentationBundle\Contract\Service\DocBlockParserInterface:
        class: Valantic\PimcoreApiDocumentationBundle\Service\DocBlockParser

    Valantic\PimcoreApiDocumentationBundle\Contract\Service\ComponentPropertyDocGeneratorInterface:
        class: Valantic\PimcoreApiDocumentationBundle\Service\ComponentPropertyDocGenerator
